# Introduction {#intro}

## Course Goals

During the course we have two main goals:

1. Develop student understanding of topics in ocean and environmental science pertinent to global climate change with a focus on activities in the Woods Hole science community.
1. Build student research skills to aid their summer internship work and future careers.

The first goal will be acheived through a series of classes on basic oceanography spanning physics, chemistry and biology. These classes will be supplimented with more advanced topics, introduced by leading researchers in the Woods Hole community, that will bring students' understanding to the frontier of current understanding.

The second goal will be acheived through working on mini-projects centered on data collected on two previous PEP cruises out of Woods Hole. Students will work in teams to build on the introductory class in oceanography to develop their understanding of a particular focus area. To do this, students will need to develop capacity in finding and reading scientific literature, creating hyptotheses, vizualizing geospatial data, summarizing results, collaborating as a team, and creating a professional research poster. The development of these skills will serve as a primer for the internship research work students will conduct over the course of the rest of the summer.

The individual classes of the course will therefore fall into one of three categories:

1. Introduction to Oceanography (4 classes): Exposure and review of key topics in oceanography
1. Advanced Topics (6 classes): Researcher-led presentation and discussion of frontier topics in Woods Hole community.
1. Research skills (8 classes): e.g. How to read literature, how to find and organize literature, visualization tools, poster development, etc.

## Format

This being an remote offering, the format might be a little different to an in-person class. The onus will be on you to read and grapple with the content and skills independently and with your peers at first before a full class discussion and review of the material.

Expect the steps in the daily routine to follow this basic pattern:

**Independent Work**: This will be work that you conduct individually and should take you somewhere between 1 and 2 hours to complete. You may be asked to do some reading, test and apply your knowledge, conduct some research, or reflect on a topic. It is likely to involve some thing to submit at the end of the period to allow us to keep track of what you have been doing, but other than participation, this work is ungraded.

**Team Work**: After the initial independent work, you will be assigned a study team and a selection of questions or activities for you to work through together on a video call. This could include reviewing independent exercises, discussing an advanced questions, or compiling a presentation for class. This is likely to take about 30 mins and no longer than one hour. As with the independent work, there is likely to be something to submit as evidence of participation.

**Class Discussion**: After you have all completed your individual and team work, we will meet as a full cohort to review the content or skills and advance the conversation. This may involve students asking clarifying questions, student presentations, instructor presentations, breakout groups or other discussion items. We will also provide a preview of the next section of classwork. This will take an hour or more.

**The total amount of hours you are expected to spend on the course (including the video class) is 3-4 hours**. This does not include time spent in other PEP professional development or social activities, nor does it include time spent spinning-up your internship research project with your mentor.

## Platforms

To deliver the class content and skills, we will be using the following platforms:

### Class Site

This site will be where we share class content and exercises. Every day's class will be explained on here including your independent and team work expected ahead of the class. If a submission is required I will [link](https://classroom.google.com/u/4/c/NjM3MjQ2MTI5OTJa/a/ODEwMTY1NzIzNjVa/details) directly to it in Google Classroom (see below).

The chapters of this site will be organized into the order of the day of the class discussions. That said, there is likely to be work on some chapters that you will need to conduct a few days in advance of the class discussion so read ahead and be tuned into what you instructors are telling you.

### Google Classroom

Google Classroom will be where we organize assignments and submissions for various component of the course. This will include both participatory submissions (i.e. ungraded for content) and graded submissions. Instructions for graded submissions will be provided on Google Classroom and may not also be covered on the Class Site.

Please sign-up for the PEP 2020 Class by doing the following:

- Go to [Google Classroom](https://classroom.google.com).
- Click on the plus symbol in the top right and select "join class".
- Enter the PEP 2020 Class code: XXXXXXX
- *NB: We've had issues in the past with some institutional emails being locked out of the PEP Google Classroom so if you get a message saying you can't join the class, please try with another personal email address or create a free gmail account to use.*

### Slack

To facilitate direct communication with and between members of the 2020 PEP Cohort, we will be using Slack. This is a direct and group messaging application that will allow us to share news and upcoming events with the whole group as well as organize smaller discussions or contact individual students. Before the 2020 PEP Program begins you will need to:

- Create and account
- Download the desktop and/or mobile app
- Anything else?!
