# Individual Development Plan

__What is an Individual Development Plan (IDP)?__

An individual development plan (IDP) is a tool you can use to achieve your short and long term goals. Building an IDP will require you to evaluate your skills, interests, and values to set specific, measurable, action-oriented, realistic, and time-bound (SMART) goals.

During this week, you will develop short term (10 week) and long term (6 months) IDPs. The short term IDP will help you and your research mentor develop a productive work plan for the summer and the long term IDP will help you identify pathways for reach your longer term goals. In addition, these IDPs will help the PEP staff and alumni further support you and your aspirations. By the ending of the week, you will have two IDPs that you will review and further refine with your research mentor. 

__Tasks to Complete Before Thursday, June 4th__    
Instructions: Please complete the following assessments. I highly encourage you to review these assessments a few days in advance because ample time for reflection will yield more thoughtful and fruitful discussions with your research mentors. 

* Links forthcoming     
1. Skills Assessment    
2. Interests Assessment       
3. Values Assessment    

__IDP Resources__
